// <auto-generated />
namespace AuthorDesign.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAuthoryOrderNum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAuthoryOrderNum));
        
        string IMigrationMetadata.Id
        {
            get { return "201511240545234_AddAuthoryOrderNum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
